config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :school_classes, except: :show
  resources :students, except: :show

  resources :tests, except: :show
  resources :test_grades, only: :index

  namespace :pdf do
    resources :tests, only: :index
    resources :templates, only: :index
  end

  namespace :api do
    resources :test_grades, only: :create

    post "/mobile_login", to: "mobile_sessions#create"
    post "/is_user_logged_in", to: "mobile_sessions#show"
    delete "/mobile_logout", to: "mobile_sessions#destroy"
  end
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :school_class
  belongs_to :user

  has_many :tests, through: :school_class
  has_many :test_grades, dependent: :destroy

  validates :name, presence: true
  validates :identifier, presence: true, uniqueness: true

  default_scope { order(:name) }

  def self.ransackable_attributes(_auth_object = nil)
    ["school_class_id"]
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  before_action :handle_school_classes_missing
  before_action :set_student, only: %i[edit update destroy]

  def index
    @search_query = current_user.students.ransack(params[:q])
    search_result = @search_query.result(distinct: true)
    @pagy, @students = pagy(search_result)
  end

  def new
    @student = Student.new
  end

  def edit; end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_path, notice: t("shared.notices.male.created",
                                           model: t("activerecord.models.student"))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @student.update(student_params)
      redirect_to students_path, notice: t("shared.notices.male.updated",
                                           model: t("activerecord.models.student"))
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path, notice: t("shared.notices.male.destroyed",
                                         model: t("activerecord.models.student"))
  end

  private

  def handle_school_classes_missing
    redirect_to root_path, alert: t("students.alert.no_school_classes") unless current_user.school_classes.any?
  end

  def set_student
    @student = current_user.students.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :identifier, :school_class_id).with_defaults(user_id: current_user.id)
  end
end

app/views/students/_form.html.erb
<%= simple_form_for @student do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs mb-3">
    <%= f.input :name, required: false %>
    <%= f.input :identifier, required: false %>
    <%= f.association :school_class, prompt: true, required: false, input_html: { class: "form-select" }, collection: current_user.school_classes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to t("shared.buttons.back"), students_path, class: "btn btn-secondary mx-2" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<%= render CenterContent::Component.new(width: 8) do %>
  <h1 class="text-center">
    <%= t("shared.titles.edit", model: t("activerecord.models.student")) %>
  </h1>

  <%= render "form" %>
<% end %>

app/views/students/index.html.erb
<%= render CenterContent::Component.new(width: 8) do %>
  <h1 class="mb-3 text-center"><%= t("activerecord.models.student").pluralize %></h1>

  <div class="col-md-5 mb-3">
    <div class="form-inputs">
      <%= search_form_for @search_query do |f| %>
        <%= f.collection_select :school_class_id_eq, current_user.school_classes, :id, :name, { include_blank: t("students.index.filter_by_school_class") }, { class: "form-select", onchange: "this.form.submit()" } %>
      <% end %>
    </div>
  </div>

  <% if @students.any? %>
    <table class="table table-hover table-responsive">

      <thead>
        <tr>
          <th scope="col"><%= t("activerecord.attributes.student.name") %></th>
          <th scope="col"><%= t("activerecord.attributes.student.identifier") %></th>
          <th scope="col"><%= t("activerecord.attributes.student.school_class") %></th>
          <th/>
        </tr>
      </thead>

      <tbody>
        <% @students.each do |student| %>

          <tr class="align-middle">
            <td>
              <%= student.name %>
            </td>

            <td>
              <%= student.identifier %>
            </td>

            <td>
              <%= student.school_class.name %>
            </td>

            <td class="align-middle text-end">
              <%= link_to t("shared.buttons.edit"), edit_student_path(id: student.id),
                                                                      class: "text-decoration-none px-2" %>

              <%= button_to t("shared.buttons.destroy"), student_path(id: student.id),
                                                                      method: :delete,
                                                                      class: "btn text-danger text-decoration-none px-2" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="d-flex justify-content-center py-2">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  <% end %>

  <% if @students.empty? %>
    <div class="alert alert-info">
      <%= t("shared.messages.no_records") %>
    </div>
  <% end %>

  <%= link_to t("shared.buttons.add"), new_student_path, class: "btn btn-primary" %>
  <%= link_to t("shared.buttons.back"), root_path, class: "btn btn-secondary mx-2" %>
<% end %>

app/views/students/new.html.erb
<%= render CenterContent::Component.new(width: 8) do %>
  <h1 class="text-center">
    <%= t("shared.titles.new", model: t("activerecord.models.student")) %>
  </h1>

  <%= render "form" %>
<% end %>