config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :school_classes, except: :show
  resources :students, except: :show

  resources :tests, except: :show
  resources :test_grades, only: :index

  namespace :pdf do
    resources :tests, only: :index
    resources :templates, only: :index
  end

  namespace :api do
    resources :test_grades, only: :create

    post "/mobile_login", to: "mobile_sessions#create"
    post "/is_user_logged_in", to: "mobile_sessions#show"
    delete "/mobile_logout", to: "mobile_sessions#destroy"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable,
         :validatable

  has_secure_token :auth_token, length: 36

  has_many :tests, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :school_classes, dependent: :destroy
  has_many :students, dependent: :destroy
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t("devise.shared.links.sign_in"), new_session_path(resource_name), class: "btn-link text-decoration-none" %>
  <br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t("devise.shared.links.sign_up"), new_registration_path(resource_name), class: "btn-link text-decoration-none" %>
  <br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t("devise.shared.links.forgot_your_password"), new_password_path(resource_name), class: "btn-link text-decoration-none" %>
  <br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t("devise.shared.links.didn_t_receive_confirmation_instructions"), new_confirmation_path(resource_name), class: "btn-link text-decoration-none" %>
  <br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "btn-link text-decoration-none" %>
  <br />
<% end %>