config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :school_classes, except: :show
  resources :students, except: :show

  resources :tests, except: :show
  resources :test_grades, only: :index

  namespace :pdf do
    resources :tests, only: :index
    resources :templates, only: :index
  end

  namespace :api do
    resources :test_grades, only: :create

    post "/mobile_login", to: "mobile_sessions#create"
    post "/is_user_logged_in", to: "mobile_sessions#show"
    delete "/mobile_logout", to: "mobile_sessions#destroy"
  end
end

app/models/test_grade.rb
# frozen_string_literal: true

class TestGrade < ApplicationRecord
  belongs_to :test
  belongs_to :student

  validates :grade, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/api/test_grades_controller.rb
# frozen_string_literal: true

module Api
  class TestGradesController < ApplicationApiController
    before_action :ensure_test_grade_params_are_present, only: :create

    def create
      test_grade = TestGrade.find_or_initialize_by(test_id: params[:test_id], student_id: params[:student_id])
      test_grade.grade = params[:grade]

      if test_grade.save
        render json: { test_grade: test_grade.grade }, status: :created
      else
        render json: { errors: test_grade.errors.full_messages }, status: :unprocessable_entity
      end
    end

    private

    def ensure_test_grade_params_are_present
      return if params[:grade].present? && params[:test_id].present? && params[:student_id].present?

      render json: { errors: I18n.t("api.test_grades.missing_params") }, status: :bad_request
    end
  end
end

app/controllers/test_grades_controller.rb
# frozen_string_literal: true

class TestGradesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @student = Student.find_by(identifier: params[:identifier])
    @test_grades = @student&.test_grades
  end
end

app/views/test_grades/index.html.erb
<%= render CenterContent::Component.new(width: 6) do %>
  <% if params[:identifier]&.empty? %>
    <div class="alert alert-danger">
      <%= t("test_grades.index.search_field_cannot_be_blank") %>
    </div>
  <% end %>

  <%= form_with url: test_grades_path, method: :get do |f| %>
    <%= f.label :identifier, t("activerecord.attributes.student.identifier"), class: "form-label" %>
    <div class="input-group mb-3">
      <%= f.search_field :identifier, class: "form-control",
          placeholder: t("test_grades.index.type_the_identifier_to_see_your_grades"), value: params[:identifier] %>
      <%= f.submit t("shared.buttons.search"), class: "btn btn-primary" %>
    </div>
  <% end %>

  <% if @student.present? %>
    <h6 class="text-center my-5"><%= "#{t('activerecord.models.student')}: #{@student.name}" %></h6>

    <% if @test_grades.present? %>
      <table class="table table-hover table-responsive">
        <thead>
          <tr>
            <th scope="col"><%= t("activerecord.models.test") %></th>
            <th scope="col"><%= t("activerecord.models.test_grade") %></th>
          </tr>
        </thead>
        <tbody>
          <% @test_grades.each do |test_grade| %>
            <tr class="align-middle">
              <td>
                <%= test_grade.test.name %>
              </td>

              <td>
                <%= test_grade.grade %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-info">
        <%= t("test_grades.index.no_grades_found") %>
      </div>
    <% end %>
  <% elsif params[:identifier].present? %>
    <div class="alert alert-danger">
      <%= t("test_grades.index.no_student_found_with_this_identifier_found", identifier: params[:identifier]) %>
    </div>
  <% end %>
<% end %>