config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :school_classes, except: :show
  resources :students, except: :show

  resources :tests, except: :show
  resources :test_grades, only: :index

  namespace :pdf do
    resources :tests, only: :index
    resources :templates, only: :index
  end

  namespace :api do
    resources :test_grades, only: :create

    post "/mobile_login", to: "mobile_sessions#create"
    post "/is_user_logged_in", to: "mobile_sessions#show"
    delete "/mobile_logout", to: "mobile_sessions#destroy"
  end
end

app/controllers/school_classes_controller.rb
# frozen_string_literal: true

class SchoolClassesController < ApplicationController
  before_action :set_school_class, only: %i[edit update destroy]

  def index
    @pagy, @school_classes = pagy(current_user.school_classes)
  end

  def new
    @school_class = SchoolClass.new
  end

  def edit; end

  def create
    @school_class = SchoolClass.new(school_class_params)

    if @school_class.save
      redirect_to school_classes_path, notice: t("shared.notices.female.created",
                                                 model: t("activerecord.models.school_class"))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @school_class.update(school_class_params)
      redirect_to school_classes_path, notice: t("shared.notices.female.updated",
                                                 model: t("activerecord.models.school_class"))
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @school_class.destroy
    redirect_to school_classes_path, notice: t("shared.notices.female.destroyed",
                                               model: t("activerecord.models.school_class"))
  end

  private

  def set_school_class
    @school_class = current_user.school_classes.find(params[:id])
  end

  def school_class_params
    params.require(:school_class).permit(:name).with_defaults(user_id: current_user.id)
  end
end

app/views/school_classes/_form.html.erb
<%= simple_form_for @school_class do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs mb-3">
    <%= f.input :name, required: false %>
  </div>

   <div class="form-actions">
     <%= f.button :submit, class: "btn btn-primary" %>
     <%= link_to t("shared.buttons.back"), school_classes_path, class: "btn btn-secondary mx-2" %>
  </div>
<% end %>

app/views/school_classes/edit.html.erb
<%= render CenterContent::Component.new(width: 8) do %>
  <h1 class="text-center">
    <%= t("shared.titles.edit", model: t("activerecord.models.school_class")) %>
  </h1>

  <%= render "form" %>
<% end %>

app/views/school_classes/index.html.erb
<%= render CenterContent::Component.new(width: 8) do %>
  <h1 class="mb-3 text-center"><%= t("activerecord.models.school_class").pluralize %></h1>

    <% if @school_classes.any? %>
      <table class="table table-hover table-responsive">
        <thead>
          <tr>
            <th scope="col"><%= t("activerecord.attributes.school_class.name") %></th>
            <th/>
          </tr>
        </thead>

        <tbody>

          <% @school_classes.each do |school_class| %>
            <tr class="align-middle">
              <td>
                <%= school_class.name %>
              </td>

              <td class="align-middle text-end">
                <%= link_to t("shared.buttons.edit"), edit_school_class_path(id: school_class.id),
                                                                              class: "text-decoration-none px-2" %>

                <%= button_to t("shared.buttons.destroy"), school_class_path(id: school_class.id),
                                                                              method: :delete,
                                                                              class: "btn text-danger text-decoration-none px-2" %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>

      <div class="d-flex justify-content-center py-2">
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    <% end %>


  <% if @school_classes.empty? %>
    <div class="alert alert-info">
      <%= t("shared.messages.no_records") %>
    </div>
  <% end %>

  <%= link_to t("shared.buttons.add"), new_school_class_path, class: "btn btn-primary" %>
  <%= link_to t("shared.buttons.back"), root_path, class: "btn btn-secondary mx-2" %>
<% end %>

app/views/school_classes/new.html.erb
<%= render CenterContent::Component.new(width: 8) do %>
  <h1 class="text-center">
    <%= t("shared.titles.new", model: t("activerecord.models.school_class")) %>
  </h1>

  <%= render "form" %>
<% end %>